version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=foo
      - DEBUG=1
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=familybudget
      - SQL_USER=familybudget
      - SQL_PASSWORD=familybudget
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_USER=familybudget
      - POSTGRES_PASSWORD=familybudget
      - POSTGRES_DB=familybudget
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
